// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Source: ingest/cadence_registry.yaml
// Regenerate: `npm run gen:coverage`
// Guarded by: app/data-coverage/drift.test.mts (fails if this file is stale).
//
// Why this exists: the /data-coverage page reads operational facts (cadence,
// volume floor, blocked reason) but must not parse YAML at runtime. This typed
// snapshot is the page's render-time source; the YAML is only ever parsed here
// and in the drift test (test-time-only dependency boundary).

export type RegistryLane = "tier-1" | "tier-1-duckdb" | "tier-2";

export interface RegistryEntry {
  name: string;
  lane: RegistryLane;
  cadence_days: number;
  tolerance_multiplier: number;
  expected_rows_min: number | null;
  schema: string | null;
  table: string | null;
  dlt_schema_name: string | null;
  freshness_table: string | null;
  inventory_id: string | null;
  inventory_key_type: "exact" | "prefix" | null;
  not_yet_running: boolean;
  note: string | null;
}

export const REGISTRY_ENTRIES: RegistryEntry[] = [
  {
    "name": "zori_swfl_duckdb",
    "lane": "tier-1-duckdb",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/market/zori_swfl.parquet",
    "inventory_key_type": "exact",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "redfin_swfl",
    "lane": "tier-1-duckdb",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/market/redfin_swfl.parquet",
    "inventory_key_type": "exact",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "hurdat2_fl",
    "lane": "tier-1-duckdb",
    "cadence_days": 365,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/environmental/hurdat2_fl.parquet",
    "inventory_key_type": "exact",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "storm_history_swfl",
    "lane": "tier-1-duckdb",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/environmental/storm_events_swfl.parquet",
    "inventory_key_type": "exact",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "usgs",
    "lane": "tier-1-duckdb",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/environmental/usgs_water_swfl.parquet",
    "inventory_key_type": "exact",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "faf5",
    "lane": "tier-1",
    "cadence_days": 365,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/faf5/",
    "inventory_key_type": "prefix",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fred_g17",
    "lane": "tier-1",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/macro/fred_g17/",
    "inventory_key_type": "prefix",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "bls_ppi",
    "lane": "tier-1",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/macro/bls_ppi/",
    "inventory_key_type": "prefix",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "census_vip",
    "lane": "tier-1",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/macro/census_vip/",
    "inventory_key_type": "prefix",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "city_pulse",
    "lane": "tier-1",
    "cadence_days": 1,
    "tolerance_multiplier": 3,
    "expected_rows_min": null,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/city_pulse/",
    "inventory_key_type": "prefix",
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "bls_laus",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": 295,
    "schema": "data_lake",
    "table": "bls_laus",
    "dlt_schema_name": "bls_laus",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "bls_qcew",
    "lane": "tier-2",
    "cadence_days": 90,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": 28,
    "schema": "data_lake",
    "table": "bls_qcew",
    "dlt_schema_name": "bls_qcew",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "census_cbp",
    "lane": "tier-2",
    "cadence_days": 365,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": 230006,
    "schema": "data_lake",
    "table": "census_cbp_fl",
    "dlt_schema_name": "census_cbp",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "usgs_tier2",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": 544,
    "schema": "data_lake",
    "table": "usgs_daily",
    "dlt_schema_name": "usgs",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fema",
    "lane": "tier-2",
    "cadence_days": 90,
    "tolerance_multiplier": 2,
    "expected_rows_min": 403542,
    "schema": "data_lake",
    "table": "fema_nfip_claims",
    "dlt_schema_name": "fema_nfip_tier2",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "leepa",
    "lane": "tier-2",
    "cadence_days": 365,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": 493918,
    "schema": "data_lake",
    "table": "leepa_parcels",
    "dlt_schema_name": "leepa_parcels_tier2",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fhfa",
    "lane": "tier-2",
    "cadence_days": 90,
    "tolerance_multiplier": 2,
    "expected_rows_min": 119903,
    "schema": "data_lake",
    "table": "fhfa_hpi",
    "dlt_schema_name": "fhfa_hpi",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fdot",
    "lane": "tier-2",
    "cadence_days": 365,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": 93295,
    "schema": "data_lake",
    "table": "fdot_aadt_fl",
    "dlt_schema_name": "fdot_aadt_tier2",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "lee_permits",
    "lane": "tier-2",
    "cadence_days": 7,
    "tolerance_multiplier": 3,
    "expected_rows_min": 1,
    "schema": "data_lake",
    "table": "lee_building_permits",
    "dlt_schema_name": "lee_permits",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "collier_permits",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": 4477,
    "schema": "data_lake",
    "table": "collier_building_permits",
    "dlt_schema_name": "collier_permits",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fl_dor_tdt",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2.5,
    "expected_rows_min": 599,
    "schema": "public",
    "table": "fl_dor_tdt_collections",
    "dlt_schema_name": null,
    "freshness_table": "public.fl_dor_tdt_collections",
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fl_dor_sales_tax",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": 36126,
    "schema": "public",
    "table": "fl_dor_sales_tax",
    "dlt_schema_name": null,
    "freshness_table": "public.fl_dor_sales_tax",
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "zori_swfl_tier2",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": 4666,
    "schema": "data_lake",
    "table": "zori_swfl",
    "dlt_schema_name": "zori_swfl",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fgcu_reri_indicators",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": 1,
    "schema": "public",
    "table": "fgcu_reri_indicators",
    "dlt_schema_name": null,
    "freshness_table": "public.fgcu_reri_indicators",
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "swfl_inc",
    "lane": "tier-2",
    "cadence_days": 7,
    "tolerance_multiplier": 3,
    "expected_rows_min": 28,
    "schema": "public",
    "table": "swfl_inc_announcements",
    "dlt_schema_name": null,
    "freshness_table": "public.swfl_inc_announcements",
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "rsw_airport_monthly",
    "lane": "tier-2",
    "cadence_days": 30,
    "tolerance_multiplier": 2,
    "expected_rows_min": 464,
    "schema": "public",
    "table": "rsw_airport_monthly",
    "dlt_schema_name": null,
    "freshness_table": "public.rsw_airport_monthly",
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": false,
    "note": null
  },
  {
    "name": "fdle_crime_swfl",
    "lane": "tier-2",
    "cadence_days": 90,
    "tolerance_multiplier": 2,
    "expected_rows_min": null,
    "schema": "public",
    "table": "fdle_crime_swfl",
    "dlt_schema_name": null,
    "freshness_table": "public.fdle_crime_swfl",
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": true,
    "note": "BLOCKED 2026-05-30 — source unfit. FIBRS parser fixed (coverage-matched denominator) + quarterly cron paused, but FIBRS county aggregates undercount the true county rate ~2-3x vs the FDLE UCR baseline (incomplete NIBRS-transition agency participation). public.fdle_crime_swfl left empty; safety-swfl dormant. Re-home to pipelines: only after a complete county source (FBI Crime Data Explorer) replaces FIBRS — see issue #59."
  },
  {
    "name": "bls_oews_swfl_tier1",
    "lane": "tier-1",
    "cadence_days": 365,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": 198,
    "schema": null,
    "table": null,
    "dlt_schema_name": null,
    "freshness_table": null,
    "inventory_id": "lake-tier1/labor/bls_oews_swfl/",
    "inventory_key_type": "prefix",
    "not_yet_running": true,
    "note": "Backfilled 220 rows (2021-2025). Next: verify GHA cron 15 May 2027, then move both bls_oews entries to pipelines:. Update CURRENT_OEWS_YEAR in constants.py when oesm26ma.zip ships (~Apr 2027)."
  },
  {
    "name": "bls_oews_swfl",
    "lane": "tier-2",
    "cadence_days": 365,
    "tolerance_multiplier": 1.5,
    "expected_rows_min": 198,
    "schema": "data_lake",
    "table": "bls_oews_swfl",
    "dlt_schema_name": "bls_oews_swfl",
    "freshness_table": null,
    "inventory_id": null,
    "inventory_key_type": null,
    "not_yet_running": true,
    "note": "Backfilled 220 rows (2021-2025). First GHA cron: 15 May 2027 — after green, move both bls_oews entries to pipelines: and update CURRENT_OEWS_YEAR=2026 in constants.py."
  }
];
