// lib/email/doc/seed-previews.ts
//
// Client-safe manifest for the template preview gallery (spec:
// 2026-07-09-template-preview-gallery-design.md). Display metadata + committed
// capture paths ONLY — derives name/description from SEED_DOCS so there is one
// source of truth, and adds the gallery grouping + asset path. Asset existence
// is guarded by seed-previews.test.ts (a template edit without a re-capture is
// a red test, never a broken tile in prod). Captures are generated by
// scripts/capture-seed-previews.mts — re-run it after any SEED_DOCS visual
// change, then commit the .webp outputs.
//
// Grouping is by JOB, not by layout (Really Good Emails' taxonomy pattern,
// crawled 07/09/2026): a visitor shops for "what should I send," not "which
// grid arrangement."

import { SEED_DOCS } from "./default-docs";

export type SeedPreviewGroup =
  "weekly" | "monthly" | "annual" | "listing" | "relationship" | "skeleton";

export const SEED_PREVIEW_GROUPS: { key: SeedPreviewGroup; title: string; pitch: string }[] = [
  {
    key: "listing",
    title: "Listing & event",
    pitch: "Every stage of a property's story — announcement, open house, price move, sold.",
  },
  {
    key: "weekly",
    title: "Weekly",
    pitch: "The rhythm senders — a pulse your readers expect, rebuilt from fresh data.",
  },
  {
    key: "monthly",
    title: "Monthly",
    pitch: "The deep reads — briefs and reports that argue with real figures.",
  },
  {
    key: "annual",
    title: "Annual",
    pitch: "A year of market moves in one send.",
  },
  {
    key: "relationship",
    title: "Relationship",
    pitch: "Introductions, welcomes, and the notes that keep you remembered.",
  },
  {
    key: "skeleton",
    title: "Blank canvases",
    pitch: "Designed structure, zero content — your story from scratch.",
  },
];

/** Every SEED_DOCS id maps to a gallery group — seed-previews.test.ts fails
 *  when a new template ships without a group (and without a capture). */
const GROUP_BY_SEED: Record<string, SeedPreviewGroup> = {
  "market-spotlight": "weekly",
  "weekly-pulse": "weekly",
  "trend-snapshot": "weekly",
  "rate-watch": "weekly",
  "market-letter": "monthly",
  "luxury-market-report": "monthly",
  "neighborhood-report": "monthly",
  "investment-brief": "monthly",
  "monthly-digest": "monthly",
  "editorial-letter": "monthly",
  "magazine-issue": "monthly",
  "year-in-review": "annual",
  "just-sold": "listing",
  "listing-feature": "listing",
  "new-listing": "listing",
  "open-house": "listing",
  "price-reduced": "listing",
  "just-sold-grid": "listing",
  "listing-digest": "listing",
  welcome: "relationship",
  minimal: "relationship",
  "agent-spotlight": "relationship",
  "stay-in-touch": "relationship",
  "skeleton-clean-white": "skeleton",
  "skeleton-dark-pro": "skeleton",
  "skeleton-agent-feature": "skeleton",
  "skeleton-listing-showcase": "skeleton",
};

export interface SeedPreview {
  id: string;
  name: string;
  description: string;
  group: SeedPreviewGroup;
  /** Root-relative committed capture, e.g. "/showcase/seed-previews/<id>.webp". */
  image: string;
}

export const SEED_PREVIEWS: SeedPreview[] = SEED_DOCS.map((s) => ({
  id: s.id,
  name: s.name,
  description: s.description,
  group: GROUP_BY_SEED[s.id],
  image: `/showcase/seed-previews/${s.id}.webp`,
}));

/** Previews of one group, in SEED_DOCS order. */
export function seedPreviewsFor(group: SeedPreviewGroup): SeedPreview[] {
  return SEED_PREVIEWS.filter((p) => p.group === group);
}

/** The overlay caption stamp — sourcing rides here, not inline per figure. */
export const SEED_PREVIEW_CAPTION = "Filled with live SWFL data · figures as of 07/09/2026";
