#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════════
// DOC INDEX GENERATOR — regenerates the corpus map that the `what-do-we-have`
// skill reads, so Claude can SEE what we already have instead of rebuilding it.
//
// *** THE FAILURE THIS EXISTS TO KILL. *** Operator, 08/05/2026: *"We see the things
// we have, we don't make up shit. We delete the shit we don't use."* Measured the same
// day: 1,533 docs, 240 with ZERO inbound mentions, 523 findable only by an ambiguous
// bare filename. And the sharpest edge — **`_RESEARCH/` is gitignored, so it is
// INVISIBLE to every repo-wide Grep.** An agent searches, finds nothing, concludes we
// do not have it, and re-derives research we already paid for. That is not a filing
// problem; it is the single most expensive bug in this repo.
//
// *** WHY A SKILL AND NOT ANOTHER MARKDOWN FILE. *** Verified live 08/05/2026 via
// crawl4ai against Anthropic's own Claude Code docs, verbatim: *"Unlike CLAUDE.md
// content, a skill's body loads only when it's used, so long reference material costs
// almost nothing until you need it."* That is exactly the requirement — a pointer that
// is always visible, a payload that costs nothing until the moment it is needed. We are
// not inventing a knowledge system; we are using the one Anthropic ships (RULE 0.9:
// don't build the highway).
//
// *** WHY GENERATED AND NEVER HAND-MAINTAINED. *** Every hand-maintained index in this
// repo has gone stale — that is documented history, not a risk. `_RESEARCH/INDEX.md`
// itself says "a research file not listed in this index does not exist," and 18 research
// files are not listed in it. A map a human must remember to update is a map that lies.
// Regenerate with:  node scripts/doc-index.mjs
//
// It reuses census() from doc-reachability.mjs rather than re-walking the tree, so the
// two can never disagree about what exists.
// ═══════════════════════════════════════════════════════════════════════════════
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { census } from "./doc-reachability.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILL_DIR = join(ROOT, ".claude", "skills", "what-do-we-have");
const OUT = join(SKILL_DIR, "INDEX.md");

/** Pull a usable one-line hook out of a doc: its first heading, plus the first line of
 *  real prose. Headings alone are often useless ("# Overview"), and prose alone often
 *  lacks the noun you would search for, so both are kept and joined. */
function hookFor(relPath) {
  let text;
  try {
    text = readFileSync(join(ROOT, relPath), "utf8");
  } catch {
    return { title: "", hook: "" };
  }
  const lines = text.split("\n");
  let title = "";
  let hook = "";
  let inFence = false;
  for (const raw of lines) {
    const line = raw.trim();
    if (/^(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence || !line) continue;
    if (!title && /^#{1,3}\s+/.test(line)) {
      title = line.replace(/^#{1,3}\s+/, "").replace(/\s+$/, "");
      continue;
    }
    // First real prose line after the title. Skip HTML comments, badges, tables, lists
    // of links — none of them describe what the document is FOR.
    if (title && !/^[<|\-*>#!]/.test(line)) {
      hook = line;
      break;
    }
  }
  // Strip markdown noise so the index stays scannable.
  const clean = (s) =>
    s
      .replace(/\*\*/g, "")
      .replace(/[`*_]/g, "")
      .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
      .replace(/\s+/g, " ")
      .trim();
  return { title: clean(title).slice(0, 110), hook: clean(hook).slice(0, 190) };
}

const r = census();
const orphanSet = new Set(r.orphans);
const nameOnlySet = new Set(r.byNameOnly);

/** Group by a meaningful area — two path segments, which is where this repo's meaning
 *  actually lives (docs/standards vs docs/superpowers are different worlds). */
function areaOf(p) {
  const parts = p.split("/");
  if (parts.length === 1) return "(repo root)";
  return parts.length >= 3 ? `${parts[0]}/${parts[1]}` : parts[0];
}

const byArea = new Map();
for (const d of r.docs) {
  const a = areaOf(d);
  if (!byArea.has(a)) byArea.set(a, []);
  byArea.get(a).push(d);
}

const areas = [...byArea.entries()].sort((a, b) => b[1].length - a[1].length);
const stamp = process.env.DOC_INDEX_DATE ?? new Date().toISOString().slice(0, 10);
const [yy, mm, dd] = stamp.split("-");
const asOf = `${mm}/${dd}/${yy}`;

const out = [];
out.push(`<!-- GENERATED by scripts/doc-index.mjs — DO NOT EDIT BY HAND. -->`);
out.push(`<!-- Regenerate: node scripts/doc-index.mjs -->`);
out.push(``);
out.push(`# EVERY DOCUMENT WE HAVE — ${r.docs.length} docs, as of ${asOf}`);
out.push(``);
out.push(
  `**Grep this file before concluding we do not have something.** It is the only place ` +
    `\`_RESEARCH/\` is visible to a repo-wide search — that directory is gitignored, so ` +
    `\`Grep\` over the repo CANNOT see it, and "my search found nothing" is not evidence of absence.`,
);
out.push(``);
out.push(
  `Markers: **[ORPHAN]** nothing in the repo points at this file — it is invisible unless ` +
    `you come through this index, and it is a DELETION CANDIDATE. **[weak]** reachable only ` +
    `by bare filename, which leads nowhere.`,
);
out.push(``);
out.push(
  `Reachability at generation: ${r.byPath.length} by path · ${r.byNameOnly.length} by name only · ` +
    `${r.orphans.length} orphaned. Re-measure with \`node scripts/doc-reachability.mjs\`.`,
);
out.push(``);

for (const [area, files] of areas) {
  out.push(`## ${area} — ${files.length}`);
  out.push(``);
  for (const f of files.sort()) {
    const { title, hook } = hookFor(f);
    const mark = orphanSet.has(f) ? " **[ORPHAN]**" : nameOnlySet.has(f) ? " *[weak]*" : "";
    const desc = [title, hook].filter(Boolean).join(" — ");
    out.push(`- \`${f}\`${mark}${desc ? ` — ${desc}` : ""}`);
  }
  out.push(``);
}

mkdirSync(SKILL_DIR, { recursive: true });
writeFileSync(OUT, out.join("\n"), "utf8");

const bytes = Buffer.byteLength(out.join("\n"), "utf8");
console.log(`WROTE ${OUT.replace(ROOT, ".")}`);
console.log(
  `  ${r.docs.length} docs across ${areas.length} areas · ${(bytes / 1024).toFixed(0)}KB`,
);
console.log(
  `  ${r.byPath.length} by path · ${r.byNameOnly.length} weak · ${r.orphans.length} ORPHAN (deletion candidates)`,
);
